prof = [
    'Dr.C.Kiran Mai', 
    'M.Gangappa', 
    'A.Kousar Nikhath', 
    'N.V.Sailaja', 
    'Chenna Basamma', 
    'Dr.K.Srinivas',
    'G.S.Ramesh', 
    'P.Bharath Kumar', 
    'Y.Bhanu Sree', 
    'Dr.M.Rajasekar', 
    'P.Radhika', 
    'A.Kousar Nikath',
    'Priyanka Singh', 
    'P.Rama Krishna', 
    'A.Madhavi', 
    'S.Swapna', 
    'G.Nagaraju', 
    'M.Venkata Krishna Rao',
    'Dr.A.Brahmananda Reddy', 
    'Priyanka singh', 
    'K.Bheema Lingappa', 
    'T.Gnana Prakash', 
    'R.Vijaya Saraswathi',
    'Dr.Y.Sagar', 
    'DR.K.MURALI KRISHNA', 
    'Priya Bhatnagar'
    ]